// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NetUIClient is the client API for NetUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetUIClient interface {
	// ListEngineSpecs returns a list of Protocol Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (NetUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type netUIClient struct {
	cc grpc.ClientConnInterface
}

func NewNetUIClient(cc grpc.ClientConnInterface) NetUIClient {
	return &netUIClient{cc}
}

func (c *netUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (NetUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NetUI_ServiceDesc.Streams[0], "/v1.NetUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &netUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NetUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type netUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *netUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *netUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.NetUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetUIServer is the server API for NetUI service.
// All implementations must embed UnimplementedNetUIServer
// for forward compatibility
type NetUIServer interface {
	// ListEngineSpecs returns a list of Protocol Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, NetUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedNetUIServer()
}

// UnimplementedNetUIServer must be embedded to have forward compatible implementations.
type UnimplementedNetUIServer struct {
}

func (UnimplementedNetUIServer) ListEngineSpecs(*ListEngineSpecsRequest, NetUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedNetUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedNetUIServer) mustEmbedUnimplementedNetUIServer() {}

// UnsafeNetUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetUIServer will
// result in compilation errors.
type UnsafeNetUIServer interface {
	mustEmbedUnimplementedNetUIServer()
}

func RegisterNetUIServer(s grpc.ServiceRegistrar, srv NetUIServer) {
	s.RegisterService(&NetUI_ServiceDesc, srv)
}

func _NetUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetUIServer).ListEngineSpecs(m, &netUIListEngineSpecsServer{stream})
}

type NetUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type netUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *netUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NetUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.NetUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetUI_ServiceDesc is the grpc.ServiceDesc for NetUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.NetUI",
	HandlerType: (*NetUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _NetUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _NetUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "net-ui.proto",
}
